spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/liulf_crm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    filters: wall,mergeStat
    data-source-name: liulf

#多数据源情况的配置
#liulf:
#  muti-datasource:
#    open: false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/ybj_test_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
#    username: root
#    password: root
#    data-source-name: otherdb

spring.datasource.liulf.driver-class: com.mysql.jdbc.Driver
spring.datasource.liulf.jdbc-url:  jdbc:mysql://127.0.0.1:3306/liulf_crm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
spring.datasource.liulf.username:  root
spring.datasource.liulf.password:  root
spring.datasource.liulf.max-wait:  10000
spring.datasource.liulf.min-idle:  8
spring.datasource.liulf.initial-size:  2
spring.datasource.liulf.validation-query:  SELECT 1
spring.datasource.liulf.test-on-borrow:  true
spring.datasource.liulf.test-while-idle:  true
spring.datasource.liulf.time-between-eviction-runs-millis:  18800
spring.datasource.liulf.remove-abandoned:  true
spring.datasource.liulf.jdbc-interceptors:  ConnectionState;SlowQueryReport(threshold=10)
